# This is a basic workflow to help you get started with Actions

name: Automatic Rebase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rebase:
    # The type of runner that the job will run on
      if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          fetch-depth:  0          

      # Runs a single command using the runners shell
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
